name: Deploy to Render

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run migrations
      run: |
        python manage.py migrate
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        DJANGO_SECRET_KEY: test-secret-key
        DJANGO_SETTINGS_MODULE: nexus_commerce.settings
        
    - name: Run tests
      run: |
        python manage.py test
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        DJANGO_SECRET_KEY: test-secret-key
        DJANGO_SETTINGS_MODULE: nexus_commerce.settings

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Trigger Render Deploy
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"